title: Yr0's Blog & Music repository
author: Yr0
email: I'll setup a new contact email
description: > # this means to ignore newlines until "baseurl:"
  Upcoming streaming event July 3. More personal music will be hosted here in the future.
theme: minima
# social link 
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  yr0-lab
show_excerpts: true # set to false to remove excerpts on the homepage
